#if !canImport(ObjectiveC)
import XCTest

extension FlowTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FlowTests = [
        ("testChangingProfileDoesNotUpdateRecurlyWithoutRecurlyAccount", testChangingProfileDoesNotUpdateRecurlyWithoutRecurlyAccount),
        ("testChangingProfileUpdatesEmailWithRecurly", testChangingProfileUpdatesEmailWithRecurly),
        ("testSubscription", testSubscription),
        ("testTeamMemberSignupForNotLoggedIn", testTeamMemberSignupForNotLoggedIn),
        ("testTeamSubscription", testTeamSubscription),
    ]
}

extension QueryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__QueryTests = [
        ("testAppend", testAppend),
        ("testSimpleQuery", testSimpleQuery),
    ]
}

extension RecurlyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RecurlyTests = [
        ("testNewSubscriptionNotification", testNewSubscriptionNotification),
        ("testPlan", testPlan),
        ("testSubscriptions", testSubscriptions),
    ]
}

extension RouteTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RouteTests = [
        ("testLandingPages", testLandingPages),
    ]
}

extension TaskTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TaskTests = [
        ("testSyncTeamMembersBillsAllTeamMembersForStandardUser", testSyncTeamMembersBillsAllTeamMembersForStandardUser),
    ]
}

extension TestBase {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TestBase = [
        ("testDecodeFormData", testDecodeFormData),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(FlowTests.__allTests__FlowTests),
        testCase(QueryTests.__allTests__QueryTests),
        testCase(RecurlyTests.__allTests__RecurlyTests),
        testCase(RouteTests.__allTests__RouteTests),
        testCase(TaskTests.__allTests__TaskTests),
        testCase(TestBase.__allTests__TestBase),
    ]
}
#endif
